import pandas as pd
import numpy as np
from scipy import stats
import random
df=pd.read_csv('auto-mpg.csv')
print(df)
print(df.dtypes=='object')
print(df.isnull().sum())
df=df.replace(to_replace='?',value=0)
d1={'horsepower':int}
df=df.astype(d1)
print(df.dtypes)

print('Mean of mpg is:', np.average(df.mpg))
print('Mean of cylinders is:',np.average(df.cylinders))
print('Mean of displacement is:',np.average(df.displacement))
print('Mean of horsepower is:', np.average(df.horsepower))
print('Mean of weight is:', np.average(df.weight))
print('Mean of acceleration is:', np.average(df.acceleration))
print('\n')
print('Median of mpg is:', np.median(df.mpg))
print('Median of cylinders is:',np.median(df.cylinders))
print('Median of displacement is:',np.median(df.displacement))
print('Median of weight is:', np.median(df.weight))
print('Median of acceleration is:', np.median(df.acceleration))
print('\n')
print('trimmed Mean of mpg is:', stats.trim_mean(df.mpg,0.25))
print('Trimmed Mean of cylinders is:',stats.trim_mean(df.cylinders,0.25))
print('Trimmed Mean of displacement is:',stats.trim_mean(df.displacement,0.25))
print('Trimmed Mean of horsepower is:', stats.trim_mean(df.horsepower,0.25))
print('Trimmed Mean of weight is:', stats.trim_mean(df.weight,0.25))
print('Trimmed Mean of acceleration is:', stats.trim_mean(df.acceleration,0.25))
lst1=random.randint(1,10)
df.insert(4,'Weights',lst1,True)
print('\n')
print('Weighted mean of mpg is:',np.average(df.mpg,weights=df.Weights))
print('Weighted mean of cylinders is:',np.average(df.cylinders,weights=df.Weights))
print('Weighted mean of displacement is:',np.average(df.displacement,weights=df.Weights))
print('Weighted mean of horsepower is:',np.average(df.horsepower,weights=df.Weights))
print('Weighted mean of weight is:',np.average(df.weight,weights=df.Weights))
print('Weighted mean of acceleration is:',np.average(df.acceleration,weights=df.Weights))